wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1685118707.799634
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 55
      3:
      - 23
      4: 3.9.13
      5: 0.15.3
      8:
      - 1
      - 3
      - 5
