wandb_version: 1

lr:
  desc: null
  value:
  - 0.001
  - 0.01
  - 0.1
batch_size:
  desc: null
  value:
  - 16
  - 32
  - 64
num_epochs:
  desc: null
  value:
  - 10
  - 20
  - 30
_wandb:
  desc: null
  value:
    python_version: 3.9.13
    cli_version: 0.15.3
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1685128015.209005
    t:
      1:
      - 1
      - 2
      - 3
      - 5
      - 41
      - 53
      - 55
      3:
      - 16
      - 23
      4: 3.9.13
      5: 0.15.3
      8:
      - 1
      - 3
      - 5
